# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: docker.io/library/fedora:32
    steps:
      - run: sudo dnf update -y
      - run: sudo dnf install -y rpm-build make gcc gcc-c++
      - checkout
      - run: make clean
      - run: make build
